# Generated by Django 4.1.12 on 2024-10-01 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bride_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_groom_name', message='El nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_groom_name', message='El nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
    ]
