# Generated by Django 4.1.12 on 2024-10-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_guest_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='will_assist',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
