# Generated by Django 4.1.12 on 2024-10-10 00:00

from django.db import migrations


def load_initial_data(apps, schema_editor):
    # Get the models from the historical version (not directly imported)
    Category = apps.get_model('home', 'GuestCategory')
    RelatedTo = apps.get_model('home', 'RelatedTo')

    # Predefined categories
    categories = [
        {'category_name': 'Familia'},
        {'category_name': 'Amigo'},
        {'category_name': 'Trabajo'},
    ]

    # Predefined related_to
    related_to = [
        {'related_name': 'Novio'},
        {'related_name': 'Novia'},
        {'related_name': 'Ambos'},
    ]

    # Add categories
    for category in categories:
        Category.objects.create(**category)

    # Add related_to values
    for related in related_to:
        RelatedTo.objects.create(**related)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_guest_additional_guests_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
